Update pr-validation.yml

diff --git a/.github/workflows/pr-validation.yml b/.github/workflows/pr-validation.yml
--- a/.github/workflows/pr-validation.yml
+++ b/.github/workflows/pr-validation.yml
@@ -17,8 +17,6 @@ jobs:
         run: |
           PR_BODY="${{ github.event.pull_request.body }}"
          
-
-          JIRA_REGEX="https:\/\/te-collinsongroup\.atlassian\.net\/browse\/[A-Z0-9-]+"
           MISSING_CHECKS=""
 
           #check reason for change
@@ -37,6 +35,18 @@ jobs:
           fi
 
 
+          JIRA_REGEX="https:\/\/te-collinsongroup\.atlassian\.net\/browse\/[A-Z]+-[0-9]+"
+          # Validate JIRA Ticket format
+          JIRA_TICKET=$(echo "$PR_BODY" | grep -oE "$JIRA_REGEX")
+          
+          if [[ -z "$JIRA_TICKET" ]]; then
+            echo "❌ **Failed:** *JIRA Ticket* is missing or has an invalid format."
+            exit 1
+          else
+            echo "✅ Pass: Valid JIRA Ticket found - $JIRA_TICKET"
+          fi
+
+
           # Validate "Developer" field
           DEV_SECTION=$(echo "$PR_BODY" | awk -F'Developer:' '/Developer:/ {print $2}' | xargs)
           DEV_WORD_COUNT=$(echo "$DEV_SECTION" | wc -w)
@@ -46,14 +56,7 @@ jobs:
             exit 1  # Fails the validation
           fi
           
-          # Validate JIRA Ticket format
-          JIRA_TICKET=$(echo "$PR_BODY" | grep -oE "$JIRA_REGEX")
-          if [[ -z "$JIRA_TICKET" ]]; then
-            echo "❌ **Failed:** *JIRA Ticket* is missing or has an invalid format."
-            exit 1  # Fails the validation
-          fi
-
-
+          
           REQUIRED_CHECKLISTS=(
             'Required databases are available.'
             'Required schemas are created through the data-platform repo.'
